openapi: 3.0.0
info:
  title: Folksoul- Musician Band
  description: Folksoul API
  version: 0.1.9

servers:
  - url: https://folksoul-api.nika-nozadze.redberryinternship.ge/api
    description: production server
  - url: http://localhost:5555/api
    description: local server  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /login:
    post:
      tags:
        - Auth  
      requestBody:
        description: JWT bearer authorization
        required: true
        content:
          application/json:
            schema: 
              type: 'object'
              properties:
                  name: 
                    type: string
                  password: 
                    type: string
            example:
              name: nikanoza
              password: dardubala
              
      responses:
        '200':
          description: login successfully
  /singers:  
    get:
      tags:
        - Members
      responses:
        '200':
          description: get all singers info successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string  
  /singers/{id}:
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: number
            example: 1
          required: true
      tags:
        - Members            
      responses:
        '200':
          description: get singer info successfully
          content:
            application/json:
              schema:
                type: "object"
  /singer/new:
    post:
      tags:
        - Members 
      requestBody:
        description: add new musician
        required: true
        content:
          application/json:
            schema: 
              type: 'object'
              properties:
                  name: 
                    type: string
                  instrument: 
                    type: string
                  orbitLength: 
                    type: number
                  color: 
                    type: string
                  biography: 
                    type: string
            example:
              name: სიმპსონოვიჩი
              instrument: გიტარა
              orbitLength: 100
              color: '#4257F5'
              biography: მერიტის ორდენის მფლობელი იამაიკელი მომღერალი და სიმღერების ავტორი. იგი ცნობილი გახდა ჯგუფთან (1963–1981) ერთად სკას, როკსტედისა და რეგის შესრულებით. მარლი რჩება რეგის ჟანრის ყველაზე ცნობილ შემსრულებლად და აღიარებულია იამაიკური მუსიკისა და რასტაფარის მოძრაობის ერთ-ერთ მთავარ ფიგურად.მარლის მუსიკაზე გავლენა იქონია მისი სამშობლოს სოციალურმა პრობლემებმა. აღიარებულია, რომ მუსიკოსმა მნიშვნელოვანი ნაბიჯი გადადგა ქვეყნის კულტურულ და პოლიტიკურ მოვლენებში წვლილის შეტანაში. მისი ცნობილი სიმღერებია და სთან ერთად შექმნილი გარდა ამისა, ცნობილია მისი სიმღერები, გამოცემული გარდაცვალების შემდეგ — „Buffalo Soldier“ და „Iron Lion Zion“. კრებული (1984), რომელიც მისი გარდაცვალებიდან სამი წლის შემდეგ გამოვიდა, წარმოადგენს რეგის ჟანრის ყველაზე გაყიდვად ალბომს, რომელიც აშშ-ში 10-ჯერ გახდა პლატინის (ანუ ალმასის) სტატუსის მფლობელი.[3] მსოფლიო მასშტაბით სულ გაიყიდა ალბომის 20 მილიონზე მეტი ასლი.   
      responses:
        '200':
          description: singer added
  /singers/edit/{id}:       
    put:
      parameters:
        - in: path
          name: id
          schema:
            type: number
            example: 1
          required: true
      tags:
        - Members
      requestBody:
        description: update singer
        required: true
        content:
          application/json:
            schema: 
              type: "object"
              properties:
                  name: 
                    type: string
                  instrument: 
                    type: string
                  orbitLength: 
                    type: number
                  color: 
                    type: string
                  biography: 
                    type: string 
            example:
              name: დურუ
              instrument: კლარნეტი
              orbitLength: 100
              color: '#4257F5'
              biography: დავიბადე 1940 წელს 
      responses:
        '200':
          description: Singer updated  
  /singers/delete/{id}:            
    delete:
      parameters:
        - in: path
          name: id
          schema:
            type: number
            example: 1
          required: true
      tags:
        - Members      
      responses:
        '200':
          description: musician removed 
  /singers-logos/{id}:
    post:
      parameters:
        - in: path
          name: id
          schema:
            type: number
            example: 1
          required: true
      tags: 
        - Members
      requestBody:
        description: add avatar
        required: true
        content: 
          multipart/form-data:
            schema:
              type: object
              properties:
                  image:
                    type: string
                    format: binary
      responses:
        '200':
          description: avatar uploaded 
  /singers-logos/edit/{id}:
    put:
      parameters:
        - in: path
          name: id
          schema:
            type: number
            example: 1
          required: true
      tags: 
        - Members
      requestBody:
        description: update avatar
        required: true
        content: 
          multipart/form-data:
            schema:
              type: object
              properties:
                  image:
                    type: string
                    format: binary
      responses:
        '200':
          description: avatar update              
  /links/new:
    post:
      tags:
        - Social-links 
      requestBody:
        description: add new link
        required: true
        content:
          application/json:
            schema: 
              type: 'object'
              properties:
                  name: 
                    type: string
                  link: 
                    type: string
            example:
              name: F1
              link: https://www.formula1.com
      responses:
        '200':
          description: new social link added                
  /links/{id}:
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: number
            example: 1
          required: true
      tags:
        - Social-links           
      responses:
        '200':
          description: get social link info successfully
          content:
            application/json:
              schema:
                type: "object"    
  /links/edit/{id}:       
    put:
      parameters:
        - in: path
          name: id
          schema:
            type: number
            example: 1
          required: true
      tags:
        - Social-links
      requestBody:
        description: update social link
        required: true
        content:
          application/json:
            schema: 
              type: "object"
              properties:
                  name: 
                    type: string
                  link:
                    type: string
            example:
              name: f1
              link: https://www.formula1.com
      responses:
        '200':
          description: social link updated    
  /links/delete/{id}:            
    delete:
      parameters:
        - in: path
          name: id
          schema:
            type: number
            example: 1
          required: true
      tags:
        - Social-links      
      responses:
        '200':
          description: social link removed  
  /links:  
    get:
      tags:
        - Social-links
      responses:
        '200':
          description: get all social links info successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string 
  /links-logos/{id}:
    post:
      parameters:
        - in: path
          name: id
          schema:
            type: number
            example: 1
          required: true
      tags: 
        - Social-links
      requestBody:
        description: add social link logo
        required: true
        content: 
          multipart/form-data:
            schema:
              type: object
              properties:
                  image:
                    type: string
                    format: binary
      responses:
        '200':
          description: social link logo uploaded
  /links-logos/edit/{id}:
    put:
      parameters:
        - in: path
          name: id
          schema:
            type: number
            example: 1
          required: true
      tags: 
        - Social-links
      requestBody:
        description: update social link logo
        required: true
        content: 
          multipart/form-data:
            schema:
              type: object
              properties:
                  image:
                    type: string
                    format: binary
      responses:
        '200':
          description: social link logo updated                        
  /band:
    post:
      tags: 
        - Band
      requestBody:
        description: create band
        required: true
        content: 
          multipart/form-data:
            schema:
              type: object
              properties:
                  description: 
                    type: string
                  name: 
                    type: string  
                  logo:
                    type: string
                    format: binary
      responses:
        '200':
          description: band created 
  /band/edit:
    put:
      tags: 
        - Band
      requestBody:
        description: update band
        required: true
        content: 
          multipart/form-data:
            schema:
              type: object
              properties:
                  description: 
                    type: string
                  name: 
                    type: string  
                  logo:
                    type: string
                    format: binary
      responses:
        '200':
          description: band updated 